### ISSUE TITLE
mpi4py not working in parallel in beamsim-jupyter

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#139]
```text
Traceback (most recent call last): 
 File "wake_formation.py", line 264, in <module>
Traceback (most recent call last):
  File "wake_formation.py", line 264, in <module>
Traceback (most recent call last):
  File "wake_formation.py", line 264, in <module>
Traceback (most recent call last):
  File "wake_formation.py", line 264, in <module>
    ptcl_dumper.dump_ptcls(ptcl_data, step_num)
  File "build/bdist.linux-x86_64/egg/rssympim/sympim_rz/io/particle_io.py", line 35, in dump_ptcls
    ptcl_dumper.dump_ptcls(ptcl_data, step_num)
  File "build/bdist.linux-x86_64/egg/rssympim/sympim_rz/io/particle_io.py", line 35, in dump_ptcls
    ptcl_dumper.dump_ptcls(ptcl_data, step_num)
  File "build/bdist.linux-x86_64/egg/rssympim/sympim_rz/io/particle_io.py", line 35, in dump_ptcls
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 268, in __init__
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 268, in __init__
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 268, in __init__
    fapl = make_fapl(driver, libver, **kwds)
    fapl = make_fapl(driver, libver, **kwds)
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 71, in make_fapl
    fapl = make_fapl(driver, libver, **kwds)
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 71, in make_fapl
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 71, in make_fapl
    kwds.setdefault('info', mpi4py.MPI.Info())
NameError: global name 'mpi4py' is not defined
    kwds.setdefault('info', mpi4py.MPI.Info())
NameError: global name 'mpi4py' is not defined
    kwds.setdefault('info', mpi4py.MPI.Info())
NameError: global name 'mpi4py' is not defined
    ptcl_dumper.dump_ptcls(ptcl_data, step_num)
  File "build/bdist.linux-x86_64/egg/rssympim/sympim_rz/io/particle_io.py", line 35, in dump_ptcls
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 268, in __init__
    fapl = make_fapl(driver, libver, **kwds)
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 71, in make_fapl
    kwds.setdefault('info', mpi4py.MPI.Info())
NameError: global name 'mpi4py' is not defined
```

**Comment by robnagler** [comment]
Took a little digging, but this seems to be the fix: https://github.com/radiasoft/download/commit/5f5ed5ca3fc0d46bb962a2114828da3c6b61bd8c

Build is going to take a while...
