### ISSUE TITLE
The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#140]
Likely caused by Tornado going to 5.x recently.
```text
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyter_client/manager.py", line 258, in start_kernel
    self.start_restarter()
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyter_client/ioloop/manager.py", line 49, in start_restarter
    kernel_manager=self, loop=self.loop,
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f97ad7daef0>) was specified.
```

**Comment by robnagler** [comment]
@ncook882 @cchall I had to back out the latest beamsim-jupyter image, because there are conflicts with tornado 5.x being release. I need to work those out, and then rebuild. 

Your containers will continue to run so if you don't restart, you'll have the latest image.

@bnash you can restart your server to get the old version.

**Comment by robnagler** [comment]
The build finally worked, and I verified on one of our internal servers. The push is happening to all Jupyter servers.

It's complicated getting the versions right since Jupyter runs on Python 3, but allows you to start Py2 kernels.
