### ISSUE TITLE
Beta job_agent: response from supervisor was None

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#191]
The job started, it seemed to have finished. There was an sbatch_status_stop in the run dir. The agent log is below. 

When I tried to start the simulation again, it asked to login again, which means that the supervisor never saw the agent, and apparently the agent is not seing the supervisor. The supervisor_uri configure is correct, and I was able to curl the server.

The job was queued and it seems to have run:

```txt
 28071087  R  nagler  YUL4xQzG-b*  4     24:00     5:59  2020-02-11T16:38:09  debug_hsw  2020-02-11T17:00:58  haswell  None
```

No errors in the sirepo_job_supervisor log around the time of the exception. There are some timeouts for docker, but not at that exact time.

```txt
upstream timed out (110: Connection timed out) while proxying upgraded connection
```
Job agent log error

```txt
exec 'sirepo' 'job_cmd' '/global/cscratch1/sd/nagler/sirepo-beta/user/YUL4xQzG/srw/YUL4xQzG-bDLYrkup-multiElectronAnimation/in-OrsGjep1PDoiX5dzJuBLWIAwGO5Zrm1A.json'
"
Feb 12 01:01:01 43268     0 /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:166:loop error=response from supervisor was None stack=Traceback (most recent call last):
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 163, in loop
    raise ValueError('response from supervisor was None')
ValueError: response from supervisor was None

Exception was printed at:

ValueError: response from supervisor was None
  File "/global/homes/n/nagler/.pyenv/versions/sirepo-beta/bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 111, in start_sbatch
    start()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 66, in start
    i.start()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
```

**Comment by robnagler** [comment]
Fixed
