### ISSUE TITLE
sirepo prod release wordpress_host failure

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#229]
Running update.sh prod sirepo is failing with missing wordpress config:

```
/root/src/radiasoft/rsconf/rsconf/pkcli/build.py:66:create_host fnl6b.bivio.biz: host failed:
Traceback (most recent call last):
  File "/root/.pyenv/versions/py3/bin/rsconf", line 11, in <module>
...
  File "<template>", line 22, in top-level template code
jinja2.exceptions.UndefinedError: 'pykern.pkcollections.PKDict object' has no attribute 'wordpress_host'
```

**Comment by robnagler** [comment]
I was in the midst of an rsconf update. sorry
