### ISSUE TITLE
pykern wheel build fails on sirepo alpha build

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#265]
When building sirepo alpha, this error message is shown, and then ignored?
```
      copying pykern/package_data/docs-conf.py.format -> build/lib/pykern/package_data
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/rscontainers/pykern/setup.py", line 50, in <module>
          'Topic :: Utilities',
        File "/rscontainers/pykern/pykern/pksetup.py", line 381, in setup
          op(**base)
        File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/setuptools/command/build_py.py", line 55, in run
          self.build_package_data()
        File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/setuptools/command/build_py.py", line 126, in build_package_data
          srcfile in self.distribution.convert_2to3_doctests):
      AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pykern
```

**Comment by robnagler** [comment]
setuptools 59.8.0 is being installed by something after pykern was install beamsim (common). Need to figure out what.

Also there's a shadowoui issue which may be irrelevant

google-auth conflict on cachetools.

```
Installing collected packages: setuptools, pykern
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.8.0
    Uninstalling setuptools-59.8.0:
      Successfully uninstalled setuptools-59.8.0
  Running setup.py install for pykern: started
  Running setup.py install for pykern: finished with status 'done'
  DEPRECATION: pykern was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A po
ssible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issue
s/8368
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is th
e source of the following dependency conflicts.
oasys1-shadowoui-advanced-tools 1.0.85 requires oasys-srwpy>=1.0.5, which is not installed.
oasys1-shadowoui-advanced-tools 1.0.85 requires oasys1>=1.2.89, which is not installed.
google-auth 1.35.0 requires cachetools<5.0,>=2.0.0, but you have cachetools 5.0.0 which is incompatible.
Successfully installed pykern-20220418.215951 setuptools-56.2.0
```

**Comment by robnagler** [comment]
rscode-bluesky is forcing the upgrade

**Comment by robnagler** [comment]
rebuilt bluesky in dev and it didn't have setuptools so probably just an old version.
